---
- name: Install prezto
  git:
    repo: https://github.com/sorin-ionescu/prezto.git
    dest: "{{ home }}/.zprezto"

- name: Add symbolic link dotfiles
  file: 
    src: "{{ home }}/.zprezto/runcoms/{{ item }}"
    dest: "{{ home }}/.{{ item }}"
    state: "link"
  with_items:
    - zlogin
    - zlogout
    - zpreztorc
    - zprofile
    - zshenv

- name: Set .zshrc
  template:
    src: .zshrc.j2
    dest: "{{ home }}/.zshrc"
    owner: "{{ user }}"
    group: "{{ user }}"

- name: Set .zshrc.custom
  template:
    src: .zshrc.custom.j2
    dest: "{{ home }}/.zshrc.custom"
    owner: "{{ user }}"
    group: "{{ user }}"

- name: Make directory .zsh.d
  file:
    path: "{{ home }}/.zsh.d"
    state: directory
    owner: "{{ user }}"
    group: "{{ user }}"

- name: Switch to zsh(without OSX)
  user:
    name: "{{ user }}"
    shell: /usr/bin/zsh
  sudo: yes
  when: ansible_os_family != 'Darwin'
