---
- name: Install prezto
  git: repo=https://github.com/sorin-ionescu/prezto.git dest=~/.zprezto

- name: Add symbolic link dotfiles
  file: 
    src: "~/.zprezto/runcoms/{{ item }}"
    dest: "~/.{{ item }}"
    state: "link"
  with_items:
    - zlogin
    - zlogout
    - zpreztorc
    - zprofile
    - zshenv

- name: Set .zshrc
  template:
    src: .zshrc.j2
    dest: "{{ home }}/.zshrc"

- name: Set .zshrc.custom
  template:
    src: .zshrc.custom.j2
    dest: "{{ home }}/.zshrc.custom"

- name: Make directory .zsh.d
  file:
    path: "{{ home }}/.zsh.d"
    state: directory
